"""Add verification_code_expiry to PendingUser

Revision ID: f762043de8d0
Revises: 0c37bb2a000c
Create Date: 2025-01-02 21:57:25.490820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f762043de8d0'
down_revision: Union[str, None] = '0c37bb2a000c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index('ix_users_email', table_name='users')
    #op.drop_index('ix_users_id', table_name='users')
    op.drop_constraint('pending_users_ibfk_1', table_name='pending_users', type_='foreignkey')
    op.drop_table('users')
    op.drop_index('ix_pending_users_email', table_name='pending_users')
    op.drop_index('ix_pending_users_id', table_name='pending_users')
    op.drop_table('pending_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('full_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('verification_code', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('verification_code_expiry', mysql.DATETIME(), nullable=True),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='pending_users_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_pending_users_id', 'pending_users', ['id'], unique=False)
    op.create_index('ix_pending_users_email', 'pending_users', ['email'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('verification_code', mysql.VARCHAR(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###
